# array_width = 60
# attr_fn_like_width = 70
# chain_width = 60
# disable_all_formatting = false
edition = "2021"
# fn_call_width = 60
# fn_params_layout = "Tall"
# force_explicit_abi = true
# hard_tabs = false
# match_arm_leading_pipes = Never
# match_block_trailing_comma = false
max_width = 120
# merget_derives = true
# newline_style = "Auto"
# remove_nested_parens = true
# reorder_imports = true
# reorder_modules = true
# short_array_element_width_threshold = 10
single_line_if_else_max_width = 120
single_line_let_else_max_width = 120
# struct_lit_width = 18
# struct_variant_width = 35
# tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
